name: Whale Tracker (LINE Bot)

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที (UTC)
  workflow_dispatch: {}      # ให้กดรันเองได้จากแท็บ Actions

jobs:
  track:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run tracker
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
          WALLET: ${{ secrets.WALLET }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          THRESHOLD_USD: "100000"
        run: python track_whale.py
