name: Whale Tracker (LINE Bot)

on:
  schedule:
    - cron: "*/5 * * * *"     # ทุก 5 นาที
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run trackers
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID: ${{ secrets.LINE_TARGET_ID }}
          WALLET: ${{ secrets.WALLET }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          THRESHOLD_USD: "100000"
          SIZE_CHANGE_PCT: "20"
          PNL_ALERT_PCT: "20"
        run: python main.py

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add state.json
            git commit -m "Update state [skip ci]" || echo "No changes"
            git push
          else
            echo "No state changes"
          fi
